spring:
  profiles:
    active: dev
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
#        dialect: org.hibernate.dialect.MySQLDialect
        hbm2ddl:
          auto: create
        jdbc:
          batch: 20
  datasource:
    url: "jdbc:mysql://localhost:3306/testdb"
    username: root
    password: rootpass
---
